name: Deploy ooh demo app

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::616114546942:role/ooh-github-role
          role-session-name: github-session
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        run: |
          cd infra
          terraform init

      - name: Terraform Format check
        run: |
          cd infra
          terraform fmt

      - name: Terraform Validate
        run: |
          cd infra
          terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          cd infra
          set -o pipefail
          terraform plan -no-color -detailed-exitcode | tee tfplan.txt
          echo "exitcode=$?" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Fail if Terraform Plan failed (syntax or auth issue)
        if: steps.plan.outputs.exitcode == '1'
        run: |
          echo "❌ Terraform plan failed with exit code 1"
          exit 1

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd infra
          terraform apply -auto-approve